spring:
  profiles:
    active: dev

server:
  port: 8787

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: business-client-dev
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.merin.businessClient: DEBUG
  file:
    name: Global-Logs/business-client-dev.log


