spring:
  profiles:
    active: prod

server:
  port: 8787

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: business-client-prod
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.merin.businessClient: WARN
  file:
    name: Global-Logs/business-client-prod.log

