spring:
  application:
    name: business-client
  profiles:
    active: dev

merin:
  message: Hi this is from GitHub

  cloud:
    config:
      uri: http://localhost:8001
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
      retry:
        initialInterval: 2000
        maxAttempts: 10

  mvc:
    servlet:
      load-on-startup: 1

server:
  port: 8787

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    prefer-ip-address: true
    hostname: Business-Client
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 1

logging:
  level:
    root: INFO
    com.merin.businessClient: TRACE
  file:
    name: Global-Logs/business-client.log

