# Client-specific configuration for the business-client application (prod environment)
spring:
  application:
    name: business-client
  cloud:
    config:
      uri: http://localhost:8001
      enabled: true

merin:
  message: "Welcome to the Business Client Production environment!"

server:
  port: 8787

# Config for specific business client services
business-client:
  feature-toggle:
    enabled: false
  custom-property:
    name: "Production Environment Property"
