https://github.com/Prajwal-Raichan/config-server/blob/master/business-client.ymlserver:
  port: 8787

merin:
  message: Hi,this message is from GitHub

spring:
  application:
    name: business-client
  profiles:
    active: dev

  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fall-fast: true
      retry:
        initialInterval: 2000
        maxAttempts: 10
  mvc:
    servlet:
      load-on-startup: 1

eureka:
  instance:
    prefer-ip-address: true
    hostname: Discovery-Client
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
    com.merin.businessClient: TRACE
  file:
    name: Global-Logs/business-client.log

