# Client-specific configuration for the business-client application (dev environment)
spring:
  application:
    name: business-client
  cloud:
    config:
      uri: http://localhost:8001
      enabled: true
  profiles:
   active: dev


merin:
  message: "Welcome to the Business Client Dev environment!"

server:
  port: 8787

# Config for specific business client services
business-client:
  feature-toggle:
    enabled: true
  custom-property:
    name: "Development Environment Property"
