server:
  port: 8001

spring:
  application:
    name: config-server

  profiles:
    active: dev

  cloud:
    config:
      server:
        git:
          uri: https://github.com/prajwal-raichan/config-server.git
          default-label: master
    fail-fast: true

eureka:
  instance:
    prefer-ip-address: true
    hostname: config-server
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registeryFetchIntervalSeconds: 1

logging:
  level:
    root: INFO
    com.merin.configServer: TRACE
  file:
    name: Global-Logs/config-server.log

management:
  endpoints:
    web:
      exposure: # Enable all the actuator endpoints
        include: "*"
  health:
    show-details: always

